export type HomeLanguage = "en" | "zh-TW";

export const homeCopy = {
  en: {
    hero: {
      leftRail: "INPUT / ANYTHING",
      kicker: "AGENT SKILL / MANUSCRIPT WORKFLOW",
      titleFirst: "Anything in.",
      titleJournal: "Journal",
      titleEnd: "out.",
      body: "Drop every source into one folder. Your agent builds the LaTeX, PDF, references, audit, and submission files—then opens a local workspace for the final edit.",
      primary: "Start with a folder",
      secondary: "Read the docs",
      proof: "MANUSCRIPT / EDITABLE",
      rightRail: "OUTPUT / JOURNAL",
    },
    install: {
      index: "01 / INSTALL",
      title: "One command to begin.",
      intro: "Run it yourself, or copy one prompt and let your agent handle installation or updates.",
      note: "Requires Node.js 18 or newer. The default target is",
    },
    demo: {
      index: "02 / SOURCE WORKSPACE",
      title: "One folder is the interface.",
      intro: "No form builder. No import ritual. Keep the full research context together.",
    },
    workflow: {
      index: "03 / WORKFLOW",
      title: "From source pile to final edit.",
      intro: "Four explicit steps. One real manuscript shared by the agent and the local editor.",
      steps: [
        {
          number: "01",
          label: "ASSEMBLE",
          title: "Start with a fresh folder.",
          copy: "Create one clean workspace and put every relevant source inside. Mixed formats are expected.",
        },
        {
          number: "02",
          label: "CONFIRM",
          title: "Choose draft or template.",
          copy: "Before reading the sources, the agent confirms a flexible draft or a manuscript matched to a supplied venue template.",
        },
        {
          number: "03",
          label: "GENERATE",
          title: "Build the complete paper.",
          copy: "Anything-to-Journal produces editable LaTeX, a compiled PDF, references, audit reports, and submission files.",
        },
        {
          number: "04",
          label: "REFINE",
          title: "Finish in one workspace.",
          copy: "Edit the same LaTeX through Codex or by hand. Save, recompile, and watch the PDF preview update automatically.",
        },
      ],
    },
    decision: {
      index: "04 / MODE GATE",
      titleBefore: "The agent asks",
      titleMiddle: "before it",
      titleAccent: "reads.",
      intro: "Format is a deliberate choice, never a silent guess. The workflow pauses before source content is opened until draft mode or a specific journal target is confirmed.",
      draftChip: "DEFAULT",
      draftTitle: "Journal draft",
      draftBody: "A clear, portable manuscript structure for review, iteration, and choosing a venue later.",
      draftItems: ["Standard article sections", "Readable LaTeX sources", "Conservative dependencies"],
      draftLink: "Use draft mode →",
      templateChip: "TARGETED",
      templateTitle: "Specific template",
      templateBody: "A manuscript aligned to the supplied journal class, example article, and submission requirements.",
      templateItems: ["Uses journal-provided files", "Preserves required structure", "Records compiler instructions"],
      templateLink: "Add a template →",
    },
    output: {
      index: "05 / OUTPUT",
      title: "A manuscript you still own.",
      intro: "Every major section stays legible. Figures remain replaceable, citations stay in a bibliography file, and the editor works on the actual generated source.",
      facts: ["Editable source", "Compiled PDF", "Upload-ready ZIP", "Local workspace"],
      bar: "DELIVERABLES / FINAL",
      editable: "EDITABLE",
      treeLabel: "Generated output folder tree",
      overleafRoute: "OVERLEAF ROUTE",
      overleafAction: "New Project → Upload Project",
      overleafBody: "Choose submission/overleaf-upload.zip. main.tex is already at the ZIP root.",
    },
    workspace: {
      index: "06 / MANUSCRIPT WORKSPACE",
      title: "Review the PDF. Edit the real LaTeX.",
      intro: "The finished paper opens in one local-only browser workspace. Codex edits and manual edits stay synchronized because both work on journal-output/manuscript/manuscript.tex.",
      points: [
        "PDF Preview opens first and scrolls through the complete paper.",
        "Save LaTeX to compile and refresh the preview automatically.",
        "External edits are detected without overwriting unsaved work.",
        "A failed compile keeps the last successful PDF visible.",
      ],
      localOnly: "LOCALHOST ONLY · NO CLOUD UPLOAD",
      chat: "Keep editing in Codex chat",
      browser: "Open the same URL in any browser",
    },
    overleaf: {
      index: "07 / HANDOFF",
      titleFirst: "One ZIP.",
      titleSecond: "Straight to Overleaf.",
      steps: [
        "Open Overleaf and choose New Project.",
        "Select Upload Project.",
        "Upload submission/overleaf-upload.zip.",
      ],
      button: "Open the Overleaf guide",
    },
    faq: {
      index: "08 / FAQ",
      title: "Questions, resolved.",
      items: [
        {
          question: "What can I put in the source folder?",
          answer: "Anything that helps explain the work: PDFs, notes, Word files, spreadsheets, CSV data, figures, transcripts, citations, code, earlier drafts, and journal instructions.",
        },
        {
          question: "Do I need to organize everything first?",
          answer: "No. Clear names help, but the skill is designed to inspect mixed material. Keep the folder dedicated to one manuscript and exclude secrets or unrelated files.",
        },
        {
          question: "How do I update the skill?",
          answer: "Run npx anything-to-journal@latest update. The updater verifies the existing skill, stages the newest published release, and replaces the old copy safely.",
        },
        {
          question: "Can I edit the manuscript in Codex and by hand?",
          answer: "Yes. Both routes edit the same generated LaTeX files. The workspace detects external changes, recompiles after saved edits, and refreshes the PDF preview.",
        },
        {
          question: "What happens if LaTeX compilation fails?",
          answer: "The workspace shows the compile error and keeps the last successful PDF available, so a broken edit never destroys the usable preview.",
        },
        {
          question: "Can I still use Overleaf?",
          answer: "Yes. Upload journal-output/submission/overleaf-upload.zip using New Project → Upload Project. The local workspace is an additional editing option, not a replacement for the existing handoff.",
        },
      ],
    },
    cta: {
      index: "READY / WHEN YOU ARE",
      titleFirst: "Make a folder.",
      titleSecond: "Make it a",
      titleAccent: "journal.",
      body: "Generate the full manuscript, then keep refining it in Codex, the local workspace, or Overleaf.",
      button: "Get started",
    },
  },
  "zh-TW": {
    hero: {
      leftRail: "輸入 / 任何資料",
      kicker: "AGENT SKILL / 論文工作流程",
      titleFirst: "Anything in.",
      titleJournal: "Journal",
      titleEnd: "out.",
      body: "把所有研究資料放進同一個資料夾。Agent 會完成 LaTeX、PDF、references、audit 與投稿檔案，接著開啟本機工作區，讓你進行最後編修。",
      primary: "從資料夾開始",
      secondary: "閱讀文件",
      proof: "論文 / 可編輯",
      rightRail: "輸出 / 論文",
    },
    install: {
      index: "01 / 安裝",
      title: "一行指令就能開始。",
      intro: "你可以自己執行指令，也可以複製一段 Prompt，交給 Agent 處理安裝或更新。",
      note: "需要 Node.js 18 以上。預設安裝位置為",
    },
    demo: {
      index: "02 / 來源工作區",
      title: "一個資料夾，就是完整介面。",
      intro: "不需要填表，也沒有繁瑣匯入流程；把完整研究脈絡放在一起即可。",
    },
    workflow: {
      index: "03 / 工作流程",
      title: "從散落資料到最後編修。",
      intro: "四個明確步驟；Agent 與本機編輯器共同操作同一份真實論文。",
      steps: [
        {
          number: "01",
          label: "整理",
          title: "建立全新的資料夾。",
          copy: "建立乾淨的工作區，把所有相關來源放進去。PDF、表格、筆記等混合格式都能處理。",
        },
        {
          number: "02",
          label: "確認",
          title: "選擇草稿或期刊模板。",
          copy: "讀取來源前，Agent 會先確認要產生彈性草稿，或依你提供的投稿期刊模板製作論文。",
        },
        {
          number: "03",
          label: "產生",
          title: "建立完整論文。",
          copy: "Anything-to-Journal 會產生可編輯 LaTeX、PDF、references、audit 報告及投稿檔案。",
        },
        {
          number: "04",
          label: "定稿",
          title: "在同一工作區完成。",
          copy: "透過 Codex 或手動編輯同一份 LaTeX；儲存後重新編譯，PDF 預覽會自動更新。",
        },
      ],
    },
    decision: {
      index: "04 / 模式確認",
      titleBefore: "Agent 會先詢問，",
      titleMiddle: "再開始",
      titleAccent: "讀取。",
      intro: "格式必須由你明確選擇，不會由系統默默猜測。來源內容開啟前，流程會暫停，直到你確認一般論文草稿或指定的期刊模板。",
      draftChip: "預設",
      draftTitle: "一般論文草稿",
      draftBody: "清楚、可攜的論文結構，適合先審閱與反覆修改，之後再決定投稿期刊。",
      draftItems: ["標準論文章節", "易讀的 LaTeX 原始碼", "保守的套件依賴"],
      draftLink: "使用草稿模式 →",
      templateChip: "指定格式",
      templateTitle: "特定期刊模板",
      templateBody: "依照你提供的期刊 class、範例論文與投稿規範建立稿件。",
      templateItems: ["使用期刊官方檔案", "保留必要結構", "記錄編譯方式"],
      templateLink: "加入期刊模板 →",
    },
    output: {
      index: "05 / 輸出",
      title: "論文始終由你掌握。",
      intro: "每個主要章節都清楚可讀；圖表可替換、引用保留在 bibliography 檔案中，編輯器直接操作實際產生的原始碼。",
      facts: ["可編輯原始碼", "已編譯 PDF", "可直接上傳 ZIP", "本機工作區"],
      bar: "交付內容 / 完整輸出",
      editable: "可編輯",
      treeLabel: "產生的輸出資料夾結構",
      overleafRoute: "OVERLEAF 上傳方式",
      overleafAction: "New Project → Upload Project",
      overleafBody: "選擇 submission/overleaf-upload.zip；main.tex 已位於 ZIP 根目錄。",
    },
    workspace: {
      index: "06 / 論文工作區",
      title: "預覽 PDF，直接編輯真正的 LaTeX。",
      intro: "論文完成後會開啟只在本機運作的瀏覽器工作區。Codex 修改與手動修改會保持同步，因為兩者都直接操作 journal-output/manuscript/manuscript.tex。",
      points: [
        "預設開啟 PDF 預覽，可直接捲動閱讀完整論文。",
        "儲存 LaTeX 後自動編譯並更新 PDF 預覽。",
        "自動偵測外部修改，不會覆蓋尚未儲存的內容。",
        "編譯失敗時仍保留上一份成功的 PDF。",
      ],
      localOnly: "僅限 LOCALHOST · 不上傳雲端",
      chat: "繼續在 Codex 聊天中修改",
      browser: "也可在一般瀏覽器開啟相同網址",
    },
    overleaf: {
      index: "07 / 交付",
      titleFirst: "一個 ZIP。",
      titleSecond: "直接前往 Overleaf。",
      steps: [
        "開啟 Overleaf，選擇 New Project。",
        "選擇 Upload Project。",
        "上傳 submission/overleaf-upload.zip。",
      ],
      button: "查看 Overleaf 指南",
    },
    faq: {
      index: "08 / 常見問題",
      title: "問題，一次說清楚。",
      items: [
        {
          question: "來源資料夾可以放什麼？",
          answer: "任何能說明研究的資料都可以：PDF、筆記、Word、試算表、CSV 數據、圖表、逐字稿、引用資料、程式碼、舊稿與期刊規範。",
        },
        {
          question: "需要先把所有資料整理好嗎？",
          answer: "不需要。清楚的檔名會有幫助，但 Skill 本來就能檢查混合資料。請讓一個資料夾只對應一篇論文，並排除機密或無關檔案。",
        },
        {
          question: "如何更新 Skill？",
          answer: "執行 npx anything-to-journal@latest update。更新器會驗證現有 Skill、暫存 npm 上最新發布版本，再安全替換舊版本。",
        },
        {
          question: "可以同時用 Codex 與手動方式修改論文嗎？",
          answer: "可以。兩種方式都修改同一份實際 LaTeX。工作區會偵測外部變更、在儲存後重新編譯，並更新 PDF 預覽。",
        },
        {
          question: "如果 LaTeX 編譯失敗會怎樣？",
          answer: "工作區會顯示編譯錯誤並保留上一份成功的 PDF，因此一次有問題的修改不會破壞可用的預覽。",
        },
        {
          question: "還是可以使用 Overleaf 嗎？",
          answer: "可以。使用 New Project → Upload Project 上傳 journal-output/submission/overleaf-upload.zip。本機工作區只是額外的編輯方式，不會取代原本的 Overleaf 交付。",
        },
      ],
    },
    cta: {
      index: "準備好就開始",
      titleFirst: "建立資料夾。",
      titleSecond: "完成一篇",
      titleAccent: "論文。",
      body: "先產生完整論文，再透過 Codex、本機工作區或 Overleaf 持續修改到定稿。",
      button: "開始使用",
    },
  },
} as const;
